# Use goreman to run `go get github.com/mattn/goreman`
etcd1: ../bin/etcd -name recovery -listen-client-urls http://localhost:4001 -advertise-client-urls http://localhost:4001 -listen-peer-urls http://localhost:7001 -initial-advertise-peer-urls http://localhost:7001 -force-new-cluster
